logging:
  level:
    org:
      springframework: info
server:
  servlet:
    context-path: /auth-service
  port: 5000
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name=org:
      postgresql: Driver:org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/application
    username: application
    password: application

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host:
  kafka:
    producer:
      bootstrap-servers: kafka-cloud-1:19092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
feign:
  hystrix:
    enabled: true

management:
  endpoint:
    info:
      enabled: true
    mappings:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: hystrix.stream

