spring:
  security:
    oauth2:
      client:
        clientId: user-management-service
        clientSecret: artem
        accessTokenUri: http://localhost:5000/auth-service/oauth/token
        grant-type: client_credentials
        scope: server
      resource:
        id: user-management-service
        tokenInfoUri: http://localhost:5000/auth-service/oauth/check_token
  kafka:
    consumer:
      bootstrap-servers: kafka-cloud-3:39092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: kafka-cloud-3:39092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host:
logging:
  level:
    org:
      springframework: info
server:
  servlet:
    context-path: /user-management-service
  port: 5050

feign:
  hystrix:
    enabled: true