spring:
  kafka:
    consumer:
      bootstrap-servers: kafka-cloud-1:19092
      group-id: group_id
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: kafka-cloud-3:39092
  rabbitmq:
    host: 172.30.223.211
    port: 5672
    username: guest
    password: guest
    virtual-host:
  data:
    cassandra:
      keyspace-name: application
      contactPoints: 172.29.171.141
      port: 9042
logging:
  level:
    org:
      springframework: info
server:
  servlet:
    context-path: /user-management-service
  port: 5050

feign:
  hystrix:
    enabled: true
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: user-management-service
      client-secret: artem
      access-token-uri: http://localhost:5000/auth-service/oauth/token
      user-authorization-uri: http://localhost:5000/auth-service/oauth/authorize
      scope: server
    resource:
      token-info-uri: http://localhost:5000/auth-service/oauth/check_token